name: Code quality
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.5
        with:
          args: --fail-threshold,0
          post-pr-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}